// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	internalversion "github.com/aquasecurity/trivy-operator/pkg/clientset/typed/v1alpha1/internalversion"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeAquasecurity struct {
	*testing.Fake
}

func (c *FakeAquasecurity) ClusterVulnerabilityReports(namespace string) internalversion.ClusterVulnerabilityReportInterface {
	return &FakeClusterVulnerabilityReports{c, namespace}
}

func (c *FakeAquasecurity) VulnerabilityReports(namespace string) internalversion.VulnerabilityReportInterface {
	return &FakeVulnerabilityReports{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeAquasecurity) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
