// Code generated by client-gen. DO NOT EDIT.

package internalversion

import (
	"github.com/aquasecurity/trivy-operator/pkg/clientset/scheme"
	rest "k8s.io/client-go/rest"
)

type AquasecurityInterface interface {
	RESTClient() rest.Interface
	ClusterVulnerabilityReportsGetter
	VulnerabilityReportsGetter
}

// AquasecurityClient is used to interact with features provided by the aquasecurity.github.io group.
type AquasecurityClient struct {
	restClient rest.Interface
}

func (c *AquasecurityClient) ClusterVulnerabilityReports(namespace string) ClusterVulnerabilityReportInterface {
	return newClusterVulnerabilityReports(c, namespace)
}

func (c *AquasecurityClient) VulnerabilityReports(namespace string) VulnerabilityReportInterface {
	return newVulnerabilityReports(c, namespace)
}

// NewForConfig creates a new AquasecurityClient for the given config.
func NewForConfig(c *rest.Config) (*AquasecurityClient, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &AquasecurityClient{client}, nil
}

// NewForConfigOrDie creates a new AquasecurityClient for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *AquasecurityClient {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new AquasecurityClient for the given RESTClient.
func New(c rest.Interface) *AquasecurityClient {
	return &AquasecurityClient{c}
}

func setConfigDefaults(config *rest.Config) error {
	config.APIPath = "/apis"
	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}
	if config.GroupVersion == nil || config.GroupVersion.Group != scheme.Scheme.PrioritizedVersionsForGroup("aquasecurity.github.io")[0].Group {
		gv := scheme.Scheme.PrioritizedVersionsForGroup("aquasecurity.github.io")[0]
		config.GroupVersion = &gv
	}
	config.NegotiatedSerializer = scheme.Codecs

	if config.QPS == 0 {
		config.QPS = 5
	}
	if config.Burst == 0 {
		config.Burst = 10
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *AquasecurityClient) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
